export const  ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'


export const SET_PRODUCTS = 'SET_PRODUCTS'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const CHANGE_SEARCH_RESULT = 'CHANGE_SEARCH_RESULT'
export const CHANGE_PRICE_FILTER = 'CHANGE_PRICE_FILTER'
export const CHANGE_RATING_FILTER = 'CHANGE_RATING_FILTER'
export const CLEAR_ALL_FILTER = 'CLEAR_ALL_FILTER'